version: "3"
services:
  wallet-couchdb:
    image: couchdb:latest
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=password
    ports:
      - "5985:5984"
  wallet-api:
    build: .
    environment:
      - PORT=5001
      - COUCH_CONNECTION_URL=http://admin:password@wallet-couchdb:5984
    depends_on:
      - wallet-couchdb
    links:
      - wallet-couchdb
    ports:
      - "5001:5001"
